spring:
  datasource:
    url: jdbc:mysql://10.124.131.73:3306/fiitsbg?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: rootMingze
    password: elvis985.
    #schema: database/import.sql
    #sql-script-encoding: utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:sqlMapper/*.xml

  thymeleaf:
    cache: false
    mode: HTML

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql